### ISSUE TITLE
String comparison should use `compareTo` instead of ==

### ISSUE THREAD

**Issue by taveratch** [OOP2018/coinpurse-5710546615#2]
https://github.com/OOP2018/coinpurse-5710546615/blob/66b2d99389384d1f606261a40bb0b26b45690464/src/coinpurse/Coin.java#L55

**Comment by 5710546615** [comment]
For String comparison, I think it should be use 'equals' than 'compareTo'

**Comment by taveratch** [comment]
Oh right, sorry.
